/EmbeddingRun2016_G/MuonEmbedding-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER:
  global_tag: 106X_dataRun2_v35
  campaign_name: UL2016
  tier: USER
  group: pog_tau_group
  application: cmsRun
  app_version: CMSSW_10_6_28
  processed_ds: MuonEmbedding-inputDoubleMu_106X_ULegacy_miniAOD-v1
  era: 2016
  primary_ds: EmbeddingRun2016_G
  description: TauEmbedding
  primary_ds_type: Data
  output_module_label: Merged
  parent_dataset: /DoubleMuon/Run2016G-v1/RAW
  origin_site_name: T1_DE_KIT_Disk
/EmbeddingRun2016_H/MuonEmbedding-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER:
  global_tag: 106X_dataRun2_v35
  campaign_name: UL2016
  tier: USER
  group: pog_tau_group
  application: cmsRun
  app_version: CMSSW_10_6_28
  processed_ds: MuonEmbedding-inputDoubleMu_106X_ULegacy_miniAOD-v1
  era: 2016
  primary_ds: EmbeddingRun2016_H
  description: TauEmbedding
  primary_ds_type: Data
  output_module_label: Merged
  parent_dataset: /DoubleMuon/Run2016G-v1/RAW
  origin_site_name: T1_DE_KIT_Disk
